# The Ethics of Torture & Terrorism 

## Overview {-}

Welcome to Unit 6!

In this unit we will be addressing a harsh and disquieting topic, namely torture and terrorism. Perhaps you’ve never thought of this as an issue open to ethical discussion. It’s just bad people and corrupt governments who use torture techniques, isn’t it, so what is there to discuss about the ethics of this practice?

That’s a fair question. This topic has not been part of the normal civilized discourse for a few centuries now. A few recent events, however, have moved it into the realm of discussion and it has, for better or worse, become a topic no one can avoid in the worlds of ethics and politics.

Torture, in the sense we will use it in this unit, involves **inflicting pain or suffering on a person by the state for the purpose of extracting information.** The usual justification offered is that this information could, conceivably, be useful in saving other human lives. In our reading by Alan Dershowitz, American lawyer and Harvard University professor emeritus, we will see a fuller definition which contains these same elements.

The ethical question we will face is whether we are ever morally justified in supporting our governments to carry out this practice. Imagine a government in possession of people who may have information which could be useful in preventing the suffering or deaths of many more people. Remember the people who may be tortured need not be guilty of any wrong doing. Their only “offence” is having information that a particular government believes could conceivably be useful in saving other lives.

To take a real-life example, in 1978, would the government of Italy have been justified in using torturous interrogation methods on a person in their possession to try to gain information which could possibly have led to the release of their former prime minister who had been captured by terrorists? The Italian police chose not to use such methods, believing their country could not withstand the introduction of torture to their culture. The prime minister was later executed by his captors. Or another: would the government of the United States be justified in using torture techniques today to try prevent a recurrence of 9/11?

In our second reading, by Michael Walzer, an American political philosopher who has worked a great deal on issues of social justice, we will shift our focus to the issue of terrorism. Once again, many of us have never considered terrorism to be an issue which is up for ethical discussion. Terrorism is evil, pure and simple, isn’t it? What’s there to discuss about the ethics of terrorism? Interestingly, arguments and reasons have been offered in support of acts of terrorism in certain cases and Walzer presents a number of them in his article. Once we understand these arguments, we will be in a position to evaluate them.

For instance, in both readings for this unit, we will see that the utilitarian argument in favour of torture is that it has the potential to save many lives and prevent much suffering by causing the suffering of only one person. We will have opportunities to discuss this argument and others, too, with our class colleagues to determine if there are any problems with them. Let’s prepare for some fascinating reading and lively discussion on an intense current social issue.


## Topics {-}

This unit is divided into the following topics:

1. Is Torture ever Justified?  
2. A Rationale for Terrorism: A Response. 


## Learning Outcomes {-}

When you have completed this unit, you should be able to:

- Define key terms in the discussions of torture and terrorism including lethal versus non-lethal torture, “ticking bomb” cases, coercive interrogation, and terrorism.
- Explain how Alan Dershowitz’s view permitting torture in certain cases arises from a utilitarian perspective.
- Describe how the question of torture pits certain widely held values against each other.
- State a rationale terrorists often use to justify their actions.
- Discuss objections to this terrorist rationale.


## Activity Checklist {-}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.

- Read the following articles of the textbook “Readings in Moral Philosophy” by Jonathan Wolff.  
   - Terror and Torture by Alan Dershowitz (p. 488-501)
   - Terror and Torture by Michael Walzer (pages 501-511) 
- Watch the videos related to the topic Terror and Torture 
- Look up current events regarding torture and terrorism.
- Take the ungraded quiz to review important concepts.


*Note that the learning activities in this course are ungraded, unless specified. You are strongly encouraged to complete them, as they are designed to help you succeed in your course assessments.*

## Assessment {-}

See the Assessment section in Moodle for assignment details and due dates.

## Resources {-}

Here are the resources you will need to complete this unit.

- Wolff, Jonathan. *An Introduction to Moral Philosophy*. New York: W. W. Norton & Company, 2018. 
- Other online resources will be provided in the unit.

## Is Torture Ever Justified?

Are governments ever justified in using torture? Are we, as citizens, ever justified in supporting them in using torturous methods? In all ethical questions, facts matter greatly and this issue is no exception. Here are a few facts which are often raised in discussing this issue.

First, many countries signed the Geneva Convention in the mid-1980s which bans torture in all forms, and yet a good number of them continue to practice or use severe forms of torture anyway. In other words, hypocrisy on this issue is rampant. To make matters worse, since it is in violation of the convention, the torture is going on behind closed doors, unacknowledged, so there are no controls.

A second fact: As Alan Dershowitz points out in the article we will read by him, if a terrorist attack like 9/11 happened, and it was later revealed that the police had deliberately refused to take action that might have prevented the attack, including torture, there would be a great outcry.

One final unsettling fact is that, while it is commonly asserted that torture does not “work” because people will say anything to end the torture, Dershowitz highlights examples of where it has been successful in extracting useful information which has saved innocent civilians. This, he says, is precisely why a good number of countries continue to use it and, even those which say they do not, often utilize other countries as third parties to carry out torturous interrogations.

Do these facts make a difference in our ethical analysis of this question? If torture is happening anyway, and would, in certain cases, be desired by the general public, is it ethically preferable, as some argue, to legalize this practice, bring it out into the open, and place some controls on it? Is this what we should be encouraging our governments to do?

Furthermore, does it make a difference whether it works or not, whether it can successfully extract information which may save other lives? If it does not matter, why then do people who oppose torture often argue that it doesn’t work? Proper ethical inquiry must apply rigorous reasoning in analyzing these facts.

These facts lead people to take differing opinions on this issue. As we read the article by Alan Derschowitz, we’ll have an opportunity to engage with a number of the questions and arguments often expressed in both defending and criticizing the use of torture.

### Activity: Read, Watch and Reflect {-}

```{block2, type='reflect'}

Read the section on terror and torture by Alan Dershowitz (p. 488-501) in your textbook *“Readings in Moral Philosophy”* by Jonathan Wolff. As you read, take notes in your Learning Journal, defining key terms and explaining key concepts. 

Next, read the article [“America is awesome…Right?”](https://ethicsunwrapped.utexas.edu/america-awesome-right){target="_blank”} From the *Ethics Unwrapped* website.

After, watch the following videos to learn more about key terms from this topic.

[Watch: *When is Torture Justified?*](https://www.youtube.com/watch?v=3548Ac9wGN8){target="_blank”}. 

In this video, Lieutenant Colonel Jon S. Jackson, a career Army officer and lawyer, takes aim at this difficult issue -Torture- drawing on his experiences as defense counsel for detainees at Guantanamo Bay, Cuba.

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube.com/embed/3548Ac9wGN8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

---

[Watch: *Is Torture Ethical? We have an answer...*](https://www.youtube.com/watch?v=MfApHodpExM){target="_blank”}

In this video, you will look at the "Ticking Bomb" thought experiment to figure out if torture is ethical or not. You will look at the issue through Kantianism, Virtue Ethics, Utilitarianism, and Egoism, then propose a solution that everyone can agree on.  

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube.com/embed/MfApHodpExM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```

## A Rationale for Terrorism: A Response. 

In this final topic, we are shifting focus from torture to terrorism and this raises an immediate question: Isn’t terrorism simply evil through and through? Shouldn’t people who commit acts of terrorism be caught and locked up, and shouldn’t that be the end of the matter? If so, then why are we discussing this issue in a course on ethics? What is there to discuss about the ethics of this practice? Surprisingly, certain people have offered justifications for acts of terrorism under certain conditions, complete with arguments and lines of reasoning. In this topic, we will have an opportunity to acquaint ourselves with some of them through reading an article by Michael Walzer, an American political philosopher who has worked a great deal on issues of social justice. In this article, he has articulated a number of the arguments that are sometimes offered in support of certain acts of terrorism along with his own critiques of them. Once we have understood them, we’ll be in a position to assess them.

### Activity: Read, Watch and Reflect {-}

```{block2, type='reflect'}

Read the section on terror and torture by Michael Walzer (p. 501-511) in your textbook *“Readings in Moral Philosophy”* by Jonathan Wolff. Take notes defining key terms and ideas. Study the chapter review summary, questions and key terms. 

Next, choose from the following videos to learn more about key terms from this topic.

[Watch: *Michael Walzer on Just War Theory*](https://www.youtube.com/watch?v=LcBovmGZSPU){target="_blank”}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube.com/embed/LcBovmGZSPU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

---

[Watch: *Michael Walzer on Just War and Terrorism*](https://www.youtube.com/watch?v=TOfS3IIqP0M){target="_blank”}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube.com/embed/TOfS3IIqP0M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

---

[Watch: *Michael Walzer: U.S. Treatment of Enemy Combatants*](https://www.youtube.com/watch?v=X_R6Lh-N2bg){target="_blank”}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube.com/embed/X_R6Lh-N2bg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

---

[Watch: *Terrorism and Just War*](https://www.youtube.com/watch?v=yZEprmCb5Pk){target="_blank”}

<div class="video-container">

<iframe width="560" height="315" src="https://www.youtube.com/embed/yZEprmCb5Pk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

</div>

```

### Activity: Current Events {-}

```{block2, type='reflect'}

For this exercise,

- Go online and search for one or two current incidents involving torture. 
- Next, apply the principles gained from both readings to these situations.
- Finally, consider whether you believe the torture used was ethically justified and give reasons for your position.

Write your thoughts in your notes and review them as you complete the assessment for this unit.

```

### Activity: Key Terms Quiz (ungraded) {-}

```{block2, type='reflect'}

In order to review some of the major concepts from the text, take the following unmarked quiz.

Although you will not be evaluated on these terms, they will assist you in the assignments for this course. Match the following terms to their correct definition.

<iframe src="https://create.twu.ca/h5p/wp-admin/admin-ajax.php?action=h5p_embed&id=12" width="781" height="315" frameborder="0" allowfullscreen="allowfullscreen" title="Phil210-Act9.4"></iframe><script src="https://create.twu.ca/h5p/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>

```

## Unit 6 Summary {-}

In this unit we will be addressing a harsh and disquieting topic, namely torture and terrorism. It’s a topic which has not been part of normal civilized discourse for a few centuries now but, for better or worse, a few recent events have moved it into the realm of discussion.  It has now become a topic no one can avoid in the worlds of ethics and politics.  We will define the terms torture and terrorism.  Then we will turn our attention to the key ethical question involved in them, namely, whether we are ever morally justified in supporting our governments to carry out this practice.


## Assessment {-}

```{block2, type='assessment'}

<span class="blockhead">Project Presentation (40%)</span>

For this presentation, you will prepare a 10–12-minute video in which you will address one of the following two issues: Animal rights or torture & terrorism.
Please note that this is an argumentative project and not simply a discussion project. Your presentation should be 12-15 minutes in length. Also note that your research for the presentation must include sources which are not Christian or supportive of your position.

Your Project Presentation should be submitted on Moodle by the end of the week 6.

*See the Assessments section for more details on submitting your Project Presentation, as well as the grading criteria.*

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, you may want to check to make sure that you are able to:

- Define key terms in the discussions of torture and terrorism including lethal versus non-lethal torture, “ticking bomb” cases, coercive interrogation, and terrorism.
- Explain how Alan Dershowitz’s view permitting torture in certain cases arises from a utilitarian perspective.
- Describe how the question of torture pits certain widely held values against each other.
- State a rationale terrorists often use to justify their actions.
- Discuss objections to this terrorist rationale.


```




