# Assignment 2: Ethics Committee Responses {.unnumbered}

## Ethics Committee Response (20%) – Due: Week 2 {.unnumbered}

This assignment may be completed as a group or individually. You may request help from your facilitator.

“Imagine you’re a member of an Ethics Committee and given the charge to evaluate and report on one of the following cases (Choose only ONE):

1. *A local manufacturing plant in your community has been accused by a citizens group of dumping waste into a nearby river. When confronted with this issue, the manufacturing company president responded by saying, "We're not dumping that much in and we're not hurting anyone". Others in the community disagree and believe this practice by the manufacturing plant is harming the environment.*

OR

2. *Should the government provide housing and a food allowance for homeless people?*

Your report must include the following:

3. a description of the issue
4. an explanation about why this description is an ethical issue
5. your recommendation for resolving the issue
6. the reasons for your recommendation

This assignment may be in essay format or PowerPoint.

Essay Format: 500 words

PowerPoint Format: 5-10 slides"

### Grading Rubric {.unnumbered}

Your group assignment will be marked according to the following criteria:

| **Criteria** | **Excellent** | **Average** | **Needs improvement** |
|----|----|----|----|
| **Identification of issues and implications** (20 points max) | Excellent explanation of issues and implications. (20 points) | Average explanation of issues and implications. (9 to 19 points) | Inadequate explanation of issues and implications. ( 0 to 8 points) |
| **Appropriate justification of approach and expected outcome** (30 points max) | Choice of appropriate justification of approach and expected outcome. (25 to 30 points) | Some inconsistencies or not all parts of the required answer. (16 to 24 points) | Major issues with the reasoning or explanation of outcome, or no reason given. (0 to 15 points) |
| **Reasonable explanation of opinion and perspectives** (20 points max) | Well-written evaluation of opinions. (17 to 20 points) | Limited explanation of own opinion on current issues in managing change. (10 to 16 points | Minimal or non-existent explanation of own opinion on current issues in managing change. (0 to 9 points) |
| **Sufficient length** (10 points max) | Report of more than 500 words. (10 points) | Report is less than 500 words. (6 to 9 points) | Minimal report. (0 to 5 points) |
| **Layout and writing** (20 points max) | Accurate grammar and spelling, structured layout. (17 to 20 points) | Some grammar and/or writing issues. (9 to 16 points) | Major writing or spelling issues; layout not appropriate. (0 to 8 points) |
|   |   |   | TOTAL |