# Assignment 1: Reflective Journal {.unnumbered}

## Reflective Journal (20%) – Due: Week 2 {.unnumbered}

Write a reflection essay on one concept from either unit 1 or 2. This essay should include:

1.  A concise description of the concept
2.  The ethical question related to this concept
3.  Your answer to this ethical question.

Be sure to include a brief explanation in support of your answer.

Essay Format: 500 words in length.

### Grading Rubric {.unnumbered}

+-------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
|                                           | **Criteria**                                                                                                                                                        | **Weighting** |
+-------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| **Comprehensiveness**                     | Evidence of having reviewed all readings and comprehensiveness of responses to questions                                                                            | /10           |
+-------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| **Critical Thinking and Self-Reflection** | Demonstration of your ability to use critical thinking and self-reflection in discussing thoughts and feelings about the course material and the course in general. | /10           |
+-------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| **Personal Application**                  | Integration of your views of the readings with your own experiences, biases, and knowledge of ethics.                                                               | /5            |
+-------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+
| **Communication**                         | Demonstration of your ability to communicate your ideas in writing and to organize your responses clearly, thoroughly, and concisely.                               | /5            |
|                                           |                                                                                                                                                                     |               |
| **Skills**                                |                                                                                                                                                                     |               |
+-------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+

### Assignment Submission {.unnumbered}

Your Reflective Journal should be submitted on Moodle by the end of the week 2