# Assignment 3: Course Reflection Essay/Video {.unnumbered}

## Course Reflection Essay/Video (60%) – Due: Week 6 {.unnumbered}

There are two options for this assignment. Choose only ONE.

Essay Option

Write a 1000-word argumentative essay on a subject of your choice based on one of the topics in the course. There are two different ways to write this essay. Choose only ONE.

1. The first way to write the essay is to defend your own argument about one of the topics. For example, perhaps you hold a unique view about free speech. Outline your argument about free speech and then discuss why your reason(s) for your conclusion is(are) a good reason. 
2. The second way to write the essay is to raise an objection against one of the views discussed in the course. If you choose this second way, you must first identify and reconstruct the argument you are going to challenge then explain your objection against this argument. 

Video Option

The second option for the final assignment is to record a video of your argument instead of writing the essay. This video should be around 7.5 minutes long and may be a PowerPoint presentation or a video of yourself articulating your view following a script. Similar to the first option, you may choose either way:

1. Defend your own argument based on one of the topics in the course; or
2. Raise an objection against one of the topics in the course.

A reminder: in both cases, just like the written essay, you must outline either your argument or the author’s original argument.

### Grading Criteria {.unnumbered}

The six required elements of the presentation mentioned above are the following:

- Explanation of the ethical dilemma you will address
- Background information to educate your audience on this issue
- Definitions of key terms related to your issue
- Thesis statement which sets out the viewpoint you will argue for
- Supporting arguments for your viewpoint
- Response to at least one objection to your viewpoint

**Grade A:** All 6 required elements are included and are presented with excellence.

**Grade B:** All 6 required elements are included and there is room for minor improvements in 2 or more of them.

**Grade C:** 1 required element is missing and/or there is room for substantial improvements in 2 or more of them.

**Grade D:** 2 or more required elements are missing and/or there is room for substantial improvements in 3 or more of them.

**Grade F**: 3 or more required elements are missing and/or there is room for substantial improvements in the material that is presented.
